postgis:
  host:       "localhost"
  port:       "5432"
  username:   "admin"

geoserver:
  url:        "http://localhost:8080/geoserver/rest"
  username:   "admin"
  password:   "geoserver"
  workspace:  "geoloader"
  srs:        "EPSG:900913"

geonetwork:
  url:        "http://localhost:8080/geonetwork/srv/en"
  username:   "admin"
  password:   "admin"
  group:      "2"
