workspaces:
  production: geoloader
  testing:    geoloader_test

geoserver:
  url:        http://localhost:8080/geoserver
  username:   admin
  password:   geoserver
  srs:        EPSG:900913

solr:
  url:        http://localhost:8080/solr/geoloader
