# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: geoloader 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "geoloader"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["David McClure"]
  s.date = "2014-02-26"
  s.email = "david.mcclure@virginia.edu"
  s.executables = ["geoloader"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/geoloader",
    "config.yaml",
    "geoloader.gemspec",
    "lib/geoloader.rb",
    "lib/geoloader/abstract/asset.rb",
    "lib/geoloader/abstract/loaders.rb",
    "lib/geoloader/abstract/tasks.rb",
    "lib/geoloader/assets/geotiff.rb",
    "lib/geoloader/assets/shapefile.rb",
    "lib/geoloader/cli.rb",
    "lib/geoloader/loaders/geonetwork.rb",
    "lib/geoloader/loaders/geotiff_geoserver.rb",
    "lib/geoloader/loaders/geotiff_solr.rb",
    "lib/geoloader/loaders/shapefile_geoserver.rb",
    "lib/geoloader/loaders/shapefile_solr.rb",
    "lib/geoloader/services/geonetwork.rb",
    "lib/geoloader/services/geoserver.rb",
    "lib/geoloader/services/solr.rb",
    "lib/geoloader/stylesheets/iso19139.xsl",
    "spec/fixtures/geotiff.tfw",
    "spec/fixtures/geotiff.tif",
    "spec/fixtures/geotiff.tif.aux.xml",
    "spec/fixtures/geotiff.tif.ovr",
    "spec/fixtures/geotiff.tif.vat.dbf",
    "spec/fixtures/geotiff.tif.xml",
    "spec/fixtures/shapefile.dbf",
    "spec/fixtures/shapefile.prj",
    "spec/fixtures/shapefile.sbn",
    "spec/fixtures/shapefile.sbx",
    "spec/fixtures/shapefile.shp",
    "spec/fixtures/shapefile.shp.xml",
    "spec/fixtures/shapefile.shx",
    "spec/helpers/fixture.rb",
    "spec/loaders/geonetwork.rb",
    "spec/loaders/geotiff_geoserver.rb",
    "spec/loaders/geotiff_solr.rb",
    "spec/loaders/shapefile_geoserver.rb",
    "spec/loaders/shapefile_solr.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/scholarslab/Geoloader"
  s.licenses = ["Apache-2.0"]
  s.rubygems_version = "2.2.2"
  s.summary = nil

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<confstruct>, [">= 0"])
      s.add_runtime_dependency(%q<rsolr-ext>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<terminal-table>, [">= 0"])
      s.add_runtime_dependency(%q<resque>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0"])
      s.add_runtime_dependency(%q<redcarpet>, [">= 0"])
      s.add_runtime_dependency(%q<jekyll>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<confstruct>, [">= 0"])
      s.add_dependency(%q<rsolr-ext>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<terminal-table>, [">= 0"])
      s.add_dependency(%q<resque>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rubyzip>, [">= 0"])
      s.add_dependency(%q<redcarpet>, [">= 0"])
      s.add_dependency(%q<jekyll>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<confstruct>, [">= 0"])
    s.add_dependency(%q<rsolr-ext>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<terminal-table>, [">= 0"])
    s.add_dependency(%q<resque>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rubyzip>, [">= 0"])
    s.add_dependency(%q<redcarpet>, [">= 0"])
    s.add_dependency(%q<jekyll>, [">= 0"])
  end
end

