# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "geoloader"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David McClure"]
  s.date = "2013-09-12"
  s.email = "david.mcclure@virginia.edu"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "geoloader.gemspec",
    "lib/geoloader.rb",
    "lib/geoloader/geotiff.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = nil

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_runtime_dependency(%q<gdal>, ["~> 0.0.5"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<gdal>, ["~> 0.0.5"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<gdal>, ["~> 0.0.5"])
  end
end

